spring:
  application:
    name: eureka-center
server:
  port: 1001
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 5